const offerData = [
    {
      img: "../src/assets/img/OCI_1.png",
      title: "18 Piece Non-stick Cookware",
      description: "18 Piece Non-stick Cookware",
      price: "₹308.00",
      discount: "₹440.00",
    },
    {
      img: "../src/assets/img/OCI_2.png",
      title: "5 in 1 Body Wash for Men",
      description: "5 in 1 Body Wash for Men",
      price: "₹32.20",
      discount: "₹35.00",
    },
    {
      img: "../src/assets/img/OCI_3.png",
      title: "Advanced Radiant Mint",
      description: "Advanced Radiant Mint",
      price: "₹14.10",
      discount: "₹15.00",
    },
    {
      img: "../src/assets/img/OCI_4.png",
      title: "Alaskan Pink Salmon",
      description: "Alaskan Pink Salmon",
      price: "₹51.30",
      discount: "₹54.00",
    },
    {
      img: "../src/assets/img/OCI_5.png",
      title: "Almonds",
      description: "Almonds",
      price: "₹17.28",
      discount: "₹18.00",
    },
    {
      img: "../src/assets/img/OCI_6.png",
      title: "Anti-Clogging Refillable Razors",
      description: "Anti-Clogging Refillable Razors",
      price: "₹66.93",
      discount: "₹69.00",
    },
    {
      img: "../src/assets/img/OCI_7.png",
      title: "Aqua Air Freshener Spray",
      description: "Aqua Air Freshener Spray",
      price: "₹175.50",
      discount: "₹195.00",
    },
    {
      img: "../src/assets/img/OCI_8.png",
      title: "Aquamar Surimi",
      description: "Aquamar Surimi",
      price: "₹42.24",
      discount: "₹44.00",
    },
    {
      img: "../src/assets/img/OCI_9.png",
      title: "Arizona Green Tea 11.5 Oz",
      description: "Arizona Green Tea 11.5 Oz",
      price: "₹19.95",
      discount: "₹21.00",
    },
    {
      img: "../src/assets/img/OCI_10.png",
      title: "Atlantic Salmon",
      description: "Atlantic Salmon",
      price: "₹18.43",
      discount: "₹19.00",
    },
    {
      img: "../src/assets/img/OCI_11.png",
      title: "Baby Dry Diapers Size 4",
      description: "Baby Dry Diapers Size 4",
      price: "₹23.75",
      discount: "₹25.00",
    },
    {
      img: "../src/assets/img/OCI_12.png",
      title: "Baby Food, Apple Strawberry",
      description: "Baby Food, Apple Strawberry",
      price: "₹43.20",
      discount: "₹45.00",
    },
    {
      img: "../src/assets/img/OCI_13.png",
      title: "Baby Food, Banana Apple Pear",
      description: "Baby Food, Banana Apple Pear",
      price: "₹42.75",
      discount: "₹45.00",
    },
    {
      img: "../src/assets/img/OCI_14.png",
      title: "Baby Food, Banana Blackberry",
      description: "Baby Food, Banana Blackberry",
      price: "₹33.25",
      discount: "₹35.00",
    },
    {
      img: "../src/assets/img/OCI_15.png",
      title: "Baby Food, Butternut Squash",
      description: "Baby Food, Butternut Squash",
      price: "₹32.01",
      discount: "₹33.00",
    },
    {
      img: "../src/assets/img/OCI_16.png",
      title: "Baby Food, Pear Cinnamon",
      description: "Baby Food, Pear Cinnamon",
      price: "₹33.25",
      discount: "₹35.00",
    },
    {
      img: "../src/assets/img/OCI_17.png",
      title: "Baby Food, Sweet Potato",
      description: "Baby Food, Sweet Potato",
      price: "₹57.23",
      discount: "₹59.00",
    },
    {
      img: "../src/assets/img/OCI_18.png",
      title: "Baby Foods, Chicken Noodle",
      description: "Baby Foods, Chicken Noodle",
      price: "₹9.80",
      discount: "₹10.00",
    },
    {
      img: "../src/assets/img/OCI_19.png",
      title: "Baby Foods, Vegetable Chicken",
      description: "Baby Foods, Vegetable Chicken",
      price: "₹23.75",
      discount: "₹25.00",
    },
    {
      img: "../src/assets/img/OCI_20.png",
      title: "Baby Oral Care Kit 5pc",
      description: "Baby Oral Care Kit 5pc",
      price: "₹42.75",
      discount: "₹45.00",
    },
    {
      img: "../src/assets/img/OCI_21.png",
      title: "Baby Oral Cleaning Stick",
      description: "Baby Oral Cleaning Stick",
      price: "₹33.25",
      discount: "₹35.00",
    },
    {
      img: "../src/assets/img/OCI_22.png",
      title: "Bauducco Wafers",
      description: "Bauducco Wafers",
      price: "₹8.82",
      discount: "₹9.00",
    },
    {
      img: "../src/assets/img/OCI_23.png",
      title: "Beef Chuck Shaved",
      description: "Beef Chuck Shaved",
      price: "₹19.60",
      discount: "₹20.00",
    },
    {
      img: "../src/assets/img/OCI_24.png",
      title: "Beef Milanesa",
      description: "Beef Milanesa",
      price: "₹16.66",
      discount: "₹17.00",
    },
    {
      img: "../src/assets/img/OCI_25.png",
      title: "Beef Short Ribs",
      description: "Beef Short Ribs",
      price: "₹40.85",
      discount: "₹43.00",
    },
    {
      img: "../src/assets/img/OCI_26.png",
      title: "Beef T-bone Steak",
      description: "Beef T-bone Steak",
      price: "₹42.75",
      discount: "₹45.00",
    },
    {
      img: "../src/assets/img/OCI_27.png",
      title: "Big Ass Brick of Soap",
      description: "Big Ass Brick of Soap",
      price: "₹43.20",
      discount: "₹45.00",
    },
    {
      img: "../src/assets/img/OCI_28.png",
      title: "Black Tea Bags, 8 oz",
      description: "Black Tea Bags, 8 oz",
      price: "₹37.05",
      discount: "₹39.00",
    },
    {
      img: "../src/assets/img/OCI_29.png",
      title: "Capsicum",
      description: "Capsicum",
      price: "₹21.56",
      discount: "₹22.00",
    },
    {
      img: "../src/assets/img/OCI_30.png",
      title: "Cashew Nut",
      description: "Cashew Nut",
      price: "₹13.30",
      discount: "₹14.00",
    },
  ];
  
  export default offerData;
  